### ISSUE TITLE
help text for `-id` argument inconsistent

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-to-scea-tools#27]
In the help text for `hca2scea-backend/script.py` the -id asks for the 'SUBMISSION_UUID' but we are generally expected to provide the project uuid. I think that changing the help text and long form argument to `PROJECT_UUID` would help prevent confusion for users of the tool.

something like

```
parser.add_argument(
        "-id",
        "--project_uuid",
        type=str,
        required=True,
        help="Please provide an ingest project id."
    )
```

**Comment by ami-day** [comment]
done
