### ISSUE TITLE
Have an optional `output path` argument

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-to-scea-tools#28]
currently the `hca-to-scea-backend/script.py` saves to a default location within the repo folder. Over time this might lead to a lot of projects being left in this folder. Perhaps allowing a user to specify a location to output the files would mitigate this as a user tends to want to copy the files elsewhere for when they do manual curation?

In the meantime it will be up to wranglers to ensure they delete outputs from the folder as they go.

**Comment by ami-day** [comment]
done.
