### ISSUE TITLE
Mismatches in fields when running from contributor spreadsheet

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-to-scea-tools#29]
When running the tool on a spreadsheet that was wrangled from a contributor rather than by the `geo-to-hca` script, there were a few assumptions that didn't hold and resulted in some mis-assignments in the sdrf file. 

Not sure the best way to approach this, perhaps the user could indicate whether it has come from the geo-to-hca script? Or do some minimal validation of the expected values to ensure invalid values aren't used. 

@ami-day also probably already has some ideas on the best way to fix it, but wanted to note down my experience to help with improving the script

The specific issues I found when I tried converting and potential work arounds:

* The `Source Name`, `Scan Name`, `Comment[RUN]`, `Assay Name`, `Extract Name` fields use the `cell_suspension.biomaterial_core.biomaterial_description` which usually has free text for contributor projects, or could be blank, which might not be ideal for these fields
* The `Comment[ENA_EXPERIMENT]` field uses the `cell_suspension.biomaterial_core.biomaterial_id` which is not usually the ENA experiment accession for contributor projects. In these cases I think in theory it would be better to use the `process.insdc_experiment.insdc_experiment_accession` in the Sequence File tab, but I am not sure that this is always present either. I think we are more likely to perhaps have the `sequence_file.insdc_run_accessions` filled out so maybe there is a way to get the ERX from the ERR from ENA API? Or maybe again there could be a validation step that checks if the field matches `"^[D|E|S]RX[0-9]+$"` and if it doesn't, leaves it blank. We could probably make a better effort to ensure the insdc_experiment accessions are filled in after archiving if it is required for the script to run properly too.
* The `Comment [BioSD_SAMPLE]` field uses the `specimen_from_organism.biomaterial_core.biomaterial_id`, not sure which accession is preferred for this field but perhaps the `specimen_from_organism.biomaterial_core.biosamples_accession` could be a backup if that field doesn't match the expected pattern for the expected accession
* the index1 sequence file wasn't put into the sdrf file `Comment[index1 file]` column (not sure if this is related or a different bug or intentional because not required by scea?)

**Comment by ami-day** [comment]
Done.
