### ISSUE TITLE
Add automatic split based on technology and species

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-to-scea-tools#3]
Add an automatic split of the produced SDRF-IDF based on species and technology.

Currently, it is expected by a wrangler to split the spreadsheet by those 2 parameters before using the tool; I would like for this to be an automatic feature.

**Comment by ami-day** [comment]
I am closing this ticket as I think we need to keep it simple and stick to parsing separate spreadsheets as separate input values. It mostly requires duplicating the spreadsheet and then deleting a select group of rows from either the donor organism and specimen from organism tabs (split by species) or from the library protocol tab (split by technology). It is in most cases a small task.
