### ISSUE TITLE
Bug/Enhancement: does not support more than 1 10X version in the same dataset

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-to-scea-tools#68]
SCEA accept projects with different 10X versions (although they do not accept multiple scRNA-seq technology types). The hca2scea tool does not currently handle 2 10X versions in the same dataset. We need to update the tool to allow for this.

**Comment by ami-day** [comment]
Done.

**Comment by idazucchi** [comment]
@ami-day and @amnonkhen to review the PR
