### ISSUE TITLE
Create PyPi package for hca-to-scea tool

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-to-scea-tools#69]
In order to integrate the hca-to-scea tool in ingest, we first need to publish the tool as a PyPi package.

Yusra has sent me the following guide to do this:
https://realpython.com/pypi-publish-python-package/

**Comment by jacobwindsor** [comment]
@ami-day @yusra-haider why do we need to do this? We don't do this with ingest-client or graph validator. I don't think we should either

**Comment by yusra-haider** [comment]
One good reason to do this could be that the hca-to-scea tool can and does get used as a stand alone tool, similar to the geo-to-hca one

**Comment by jacobwindsor** [comment]
The same could be said for ingest-client and graph validator. We don't use them as standalone tools and maintaining versioning and publishing to PyPi is another maintenance step. Unless we have intentions to use this as standalone tool I don't think this is a good idea

**Comment by jacobwindsor** [comment]
If it gets used as a standalone tool then I agree

**Comment by ami-day** [comment]
Branch: https://github.com/ebi-ait/hca-to-scea-tools/tree/feature-69-create-pypi-package

**Comment by idazucchi** [comment]
@ami-day will do some updates and tag all devs for review

**Comment by ami-day** [comment]
Pull request for first try: https://github.com/ebi-ait/hca-to-scea-tools/pull/72

**Comment by ofanobilbao** [comment]
Ami has updated based on Jacob's comments. She has not tried to instal it yet

**Comment by ipediez** [comment]
@ami-day to try and install this

**Comment by prabh-t** [comment]
Amnon to check this today.

**Comment by ami-day** [comment]
Made fixes to the setup file, and other fixes in the repo

**Comment by ESapenaVentura** [comment]
@ami-day still working on this, no further action needed

**Comment by ami-day** [comment]
Ready for review now, linked the pull request.

**Comment by ami-day** [comment]
Done: https://pypi.org/project/hca2scea/
